(async()=>{
 const grid=document.querySelector('#freebrick2,#freebrick4');if(!grid)return;
 const source=location.href,detail=grid.id==='freebrick4';let current=TS.index(source),last=TS.max(document,source),busy=false,failed=false;
 grid.classList.add('ts-grid');const status=document.createElement('div');status.className='ts-status';grid.after(status);
 const button=document.createElement('button');button.className='ts-download';button.textContent=detail?'下載這本相簿':'選擇相簿下載';button.onclick=()=>chrome.runtime.sendMessage({type:'open'});document.body.append(button);
 // Replace the site's page-bound gallery with a native dialog that also handles appended cards.
 if(detail){const dialog=document.createElement('dialog'),img=document.createElement('img'),close=document.createElement('button');img.style='max-width:85vw;max-height:80vh';close.textContent='關閉';close.onclick=()=>dialog.close();dialog.append(close,img);document.body.append(dialog);grid.addEventListener('click',e=>{const a=e.target.closest('a.photo-gallery');if(!a)return;e.preventDefault();e.stopImmediatePropagation();img.src=a.href;dialog.showModal();},true);}
 const seen=new Set([...grid.querySelectorAll('a[href]')].map(a=>a.href));
 function update(){status.textContent=`已載入 ${grid.children.length} ${detail?'張照片':'本相簿'}（頁 ${current} / ${last}）`+(current>=last?' · 全部載入完成':' · 往下捲動繼續');}
 async function load(){if(busy||current>=last||failed)return;busy=true;status.textContent='載入下一頁…';try{const d=await TS.doc(TS.page(source,current+1));const next=d.querySelector('#'+grid.id);if(!next||!next.children.length)throw Error('找不到相簿內容');last=Math.max(last,TS.max(d,TS.page(source,current+1)));let count=0;for(const c of next.children){const a=c.querySelector('a[href]');if(!a)continue;const href=new URL(a.getAttribute('href'),source).href;if(seen.has(href))continue;seen.add(href);const copy=c.cloneNode(true);for(const x of copy.querySelectorAll('[id]'))x.removeAttribute('id');copy.removeAttribute('id');for(const x of copy.querySelectorAll('script'))x.remove();for(const x of [copy,...copy.querySelectorAll('*')])for(const attr of [...x.attributes])if(/^on/i.test(attr.name))x.removeAttribute(attr.name);for(const x of copy.querySelectorAll('a[href]'))x.href=new URL(x.getAttribute('href'),source).href;grid.append(copy);count++;}if(!count)throw Error('下一頁未提供新內容，已停止');current++;update();}catch(e){failed=true;status.textContent='載入失敗：'+e.message+'（點此重試）';status.onclick=()=>{failed=false;load();};document.querySelectorAll('.pagination').forEach(x=>x.hidden=false);}finally{busy=false;if(!failed&&current<last&&status.getBoundingClientRect().top<innerHeight+1000)setTimeout(load,300);}}
 document.querySelectorAll('.pagination').forEach(x=>x.hidden=true);update();
 new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))load();},{rootMargin:'1000px'}).observe(status);
 addEventListener('scroll',()=>{if(status.getBoundingClientRect().top<innerHeight+1000)load();},{passive:true});
})();
