const $=id=>document.getElementById(id);let controller,albums=[],running=false;
const source=TS.allowed(new URL(location.href).searchParams.get('source')).href;
function status(s){$('status').textContent=s;}
function lock(value){running=value;for(const id of ['scan','all','none','start'])$(id).disabled=value; $('cancel').disabled=!value;for(const x of document.querySelectorAll('input'))x.disabled=value;}
function render(){ $('list').replaceChildren();albums.forEach((a,i)=>{const label=document.createElement('label'),box=document.createElement('input');box.type='checkbox';box.value=i;box.checked=true;label.append(box,document.createTextNode(a.name));$('list').append(label);});$('start').disabled=!albums.length;}
async function scan(){lock(true);controller=new AbortController();try{albums=[];const seen=new Set();let last=1;for(let p=1;p<=last;p++){status(`掃描相簿列表 ${p} / ${last}`);const url=TS.page(source,p),d=await TS.doc(url,controller.signal);if(!d.querySelector('#freebrick2'))throw Error('找不到相簿列表');last=Math.max(last,TS.max(d,url));if(last>2000)throw Error('分頁數異常');for(const a of TS.albums(d))if(!seen.has(a.id)){seen.add(a.id);albums.push(a);}}render();status(`找到 ${albums.length} 本相簿`);}catch(e){albums=[];status('掃描停止：'+e.message+'；請重新掃描。');render();}finally{lock(false);$('start').disabled=!albums.length;}}
$('scan').onclick=scan;$('all').onclick=()=>document.querySelectorAll('input').forEach(x=>x.checked=true);$('none').onclick=()=>document.querySelectorAll('input').forEach(x=>x.checked=false);$('cancel').onclick=()=>controller?.abort();
async function save(blob,filename,signal){const url=URL.createObjectURL(blob);try{const id=await chrome.downloads.download({url,filename,conflictAction:'uniquify',saveAs:false});await new Promise((resolve,reject)=>{let timer;const done=()=>{clearInterval(timer);chrome.downloads.onChanged.removeListener(change);signal.removeEventListener('abort',abort);};const abort=()=>{chrome.downloads.cancel(id);done();reject(Error('已停止'));};const check=async()=>{try{const [d]=await chrome.downloads.search({id});if(d?.state==='complete'){done();resolve();}else if(d?.state==='interrupted'){done();reject(Error(d.error||'下載中斷'));}}catch(e){done();reject(e);}};const change=d=>{if(d.id===id)check();};chrome.downloads.onChanged.addListener(change);signal.addEventListener('abort',abort,{once:true});timer=setInterval(check,1000);if(signal.aborted)abort();else check();});}finally{URL.revokeObjectURL(url);}}
$('start').onclick=async()=>{const selected=[...document.querySelectorAll('input:checked')].map(x=>albums[Number(x.value)]);if(!selected.length)return;lock(true);controller=new AbortController();const signal=controller.signal;$('log').textContent='';try{for(const a of selected){if(signal.aborted)throw Error('已停止');const photos=[],seen=new Set();let last=1;for(let p=1;p<=last;p++){status(`${a.name} · 掃描照片頁 ${p} / ${last}`);const url=TS.page(a.url,p),d=await TS.doc(url,signal);if(!d.querySelector('#freebrick4'))throw Error('找不到照片內容');last=Math.max(last,TS.max(d,url));if(last>2000)throw Error('分頁數異常');for(const photo of TS.photos(d))if(!seen.has(photo.url)){seen.add(photo.url);photos.push(photo);}}if(!photos.length)throw Error('相簿沒有照片');const entries=[];let size=0;for(let i=0;i<photos.length;i++){status(`${a.name} · 原圖 ${i+1} / ${photos.length}`);const p=photos[i],r=await TS.get(p.url,signal,true);if(!r.headers.get('content-type')?.startsWith('image/'))throw Error('原圖回應不是圖片');const data=new Uint8Array(await r.arrayBuffer());size+=data.length;if(size>512*1024*1024)throw Error('單本相簿超過 512 MiB，已停止以避免記憶體不足');const ext=new URL(p.url).pathname.match(/\.(jpe?g|png|webp|gif)$/i)?.[0]||'.jpg';entries.push({name:String(i+1).padStart(4,'0')+'_'+TS.name(p.name)+ext,data});}status(`${a.name} · 建立 ZIP…`);await save(makeZip(entries),TS.name(a.name)+'.zip',signal);$('log').textContent+=`✓ ${a.name}：${photos.length} 張\n`; }status('選取相簿下載完成');}catch(e){status('下載停止：'+e.message+'；已完成的 ZIP 保留，可重新選取其餘相簿。');}finally{lock(false);}};
(async()=>{if(new URL(source).pathname.endsWith('School-Album-Detail')){$('scan').hidden=true;try{const d=await TS.doc(TS.page(source,1));albums=[{url:TS.page(source,1),name:d.querySelector('h2')?.textContent.replace(/^相簿名稱\s*[:：]\s*/,'').trim()||'相簿'}];render();status('目前相簿已就緒，下載會掃描全部照片頁。');}catch(e){status(e.message);}}else status('按「掃描完整相簿列表」取得所有頁面，可選一本、多本或全部。');})();
